WHENEVER SQLERROR CONTINUE;

ALTER SESSION SET CONTAINER = XEPDB1;

DROP USER electronics_app CASCADE;

CREATE USER electronics_app IDENTIFIED BY electronics_app_password
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO electronics_app;
GRANT CREATE TABLE TO electronics_app;
GRANT CREATE SEQUENCE TO electronics_app;
GRANT CREATE TRIGGER TO electronics_app;
GRANT CREATE PROCEDURE TO electronics_app;
GRANT CREATE VIEW TO electronics_app;
