WHENEVER SQLERROR EXIT SQL.SQLCODE;

CONNECT electronics_app/electronics_app_password@//oracle:1521/XEPDB1;

CREATE SEQUENCE seq_roles START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_users START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_staff START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_tools START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_elements START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_documents START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_devices START WITH 1 INCREMENT BY 1 NOCACHE;
